# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: X的博客
description: > # this means to ignore newlines until "baseurl:"
  技术改变世界
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.xjh1994.com" # the base hostname & protocol for your site
github_username:  xjh1994

# Build settings
markdown: kramdown
